name: isar_test
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0
  path: ^1.8.2

dev_dependencies:
  build_runner: ^2.2.1
  isar_generator: ^3.0.0
  lints: ^2.0.0
  test: ^1.21.6
